resolver: lts-7.14

packages:
- .
- jarify
- jni
- jvm
- jvm-streaming
- jarify/apps/hello

extra-deps:
- choice-0.2.0
- inline-c-0.5.6.1
- thread-local-storage-0.1.1

skip-ghc-check: true

nix:
  # Requires Stack >= 1.2.
  shell-file: shell.nix

docker:
  enable: false
  image: tweag/inline-java
  stack-exe: image
