resolver: nightly-2025-07-12

packages:
- jni
- jvm
- .

extra-deps:
- linear-base-0.5.0

ghc-options:
  "$locals": -Wall -Werror

nix:
  shell-file: ./shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]
