steps:
  - label: "Run tests (Bazel)"
    command: |
      echo "build --host_platform=@rules_haskell//haskell/platforms:linux_x86_64_nixpkgs" > .bazelrc.local
      nix-shell --pure --run 'bazel test --test_output=all //...'
    timeout: 30
  - label: "Run tests (Stack)"
    command: |
      nix-shell --pure --run 'stack --nix build --pedantic --test --bench --no-run-benchmarks'
    timeout: 30
  - label: "Install linear-types enabled GHC"
    command: |
      nix-shell shell-linear-types.nix --command ''
    timeout: 120
    key: "install-linear-ghc"
  - label: "Run tests (linear-types + Stack)"
    command: |
        nix-shell --pure --run 'stack --nix --stack-yaml stack-linear.yaml build --pedantic --test jni jvm inline-java'
    timeout: 60
    depends_on: "install-linear-ghc"
