resolver: lts-7.14

packages:
- .
- apps/hello

extra-deps:
- choice-0.1.1.0
- jni-0.2.2
- jvm-0.1.2
- jvm-streaming-0.1
- sparkle-0.3
- thread-local-storage-0.1.0.3

explicit-setup-deps:
  bench: true

nix:
  # Requires Stack >= 1.2.
  shell-file: shell.nix

skip-ghc-check: true
