name: master-build-test-workflow
on: 
  push:
    branches:
      - "master"
jobs:
  master-build-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-21.05

      - name: Setup temporary cache
        run: |
            mkdir -p $HOME/.cache/bazel

      - name: Setup .bazelrc
        run: |
            echo "common --disk_cache=$HOME/.cache/bazel" >> .bazelrc.local

      - name: Prefetch Stackage snapshot
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            nix-shell --pure --run \
              'cmd="bazel fetch @stackage//... "; $cmd || $cmd || $cmd'

      - name: Build all
        run: |
            nix-shell --pure --run 'bazel build //...'

      - name: Run tests
        run: |
            nix-shell --pure --run 'bazel test --test_output=all //...'
